spring:
  output:
    ansi:
      enabled: always

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:~/db_clinic
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
